server:
  port: 8084
  tomcat:
    max-swallow-size: 100MB
spring:
  application:
    name: pdf2epubService
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://47.97.7.63:3306/conveter?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: zqzl
      password: zqzl123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
jpa:
  database: mysql
  show-sql: false  #展示SQL语句
  generate-ddl: true  #是否自动建表
  hibernate:
    ddl-auto: update
    naming:
      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL57Dialect
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
com:
  path:
    EpubPath: D:\data\pdf\Test\EpubTotal
    PdfPath: D:\data\pdf\Test\PdfTotal
    HtmlPath: D:\data\pdf\Test\HtmlTotal
    TxtPath: D:\data\pdf\Test\TxtTotal
logging:
  level:
    cn.itcast: debug
    com.zjw.pdf_epub_provider.dao: trace
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
  config: classpath:logback-spring.xml
